// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_ixFqc4mfTgMedqqW1ZJtLvBX0-PVTM',
    appId: '1:498580446520:android:ca8ad570a7c1b5c9c135cd',
    messagingSenderId: '498580446520',
    projectId: 'tindart-8c83b',
    storageBucket: 'tindart-8c83b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCscmSjYkpBK6r3KuyW4fI29bXusLaalZQ',
    appId: '1:498580446520:ios:6275536b0067c79ac135cd',
    messagingSenderId: '498580446520',
    projectId: 'tindart-8c83b',
    storageBucket: 'tindart-8c83b.firebasestorage.app',
    androidClientId: '498580446520-inqkn6pbj7e7amjqd5sp4v9adtf8ljsn.apps.googleusercontent.com',
    iosClientId: '498580446520-2ucvd1ugvn7n637bkq51vaojaofg9o8g.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.tindart',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCp3qUnSLD_KPX9E-4-wIB3MzNSg1urj3w',
    appId: '1:498580446520:web:3ab73dc38b951e67c135cd',
    messagingSenderId: '498580446520',
    projectId: 'tindart-8c83b',
    authDomain: 'tindart-8c83b.firebaseapp.com',
    storageBucket: 'tindart-8c83b.firebasestorage.app',
    measurementId: 'G-JG1BPBXNH1',
  );
}